# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('problems', models.TextField(null=True)),
                ('acquiredCompetences', models.TextField(null=True)),
                ('parentSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentDisplayer.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(to='contentDisplayer.Tag'),
        ),
    ]
