# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentDisplayer', '0002_auto_20161208_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='problems',
            new_name='challenges',
        ),
    ]
